version: '3.8'
services:
  postgres:
    container_name: database
    restart: always
    build: ./src/db
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - custom_network
    volumes:
      - ./src/db/data:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT}
  node:
    container_name: application
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - custom_network
    volumes:
      - ./src:/app/src
networks:
  custom_network:
    driver: bridge